---
- name: Add MongoDB community repository
  ansible.builtin.yum_repository:
    name: mongodb-org-6.0.1
    file: mongodb-org-6.0.1
    description: MongoDB community repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/6.0/x86_64/
    gpgcheck: true
    gpgkey: https://www.mongodb.org/static/pgp/server-6.0.asc
    enabled: true

- name: Install MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Make run directory
  ansible.builtin.file:
    path: "/var/run/{{ mongod_name }}"
    state: directory
    owner: "{{ mongod_user }}"
    group: "{{ mongod_group }}"
    mode: "0755"

- name: Make data directory
  ansible.builtin.file:
    path: "{{ mongod_data_path }}"
    state: directory
    owner: "{{ mongod_user }}"
    group: "{{ mongod_group }}"
    mode: "0755"

- name: Create config file
  ansible.builtin.template:
    src: "{{ mongod_config_template }}"
    dest: "/etc/{{ mongod_name }}.conf"
    owner: "{{ mongod_user }}"
    group: "{{ mongod_group }}"
    mode: "0644"
  notify:
    - Restart mongod service

- name: Create systemd file
  ansible.builtin.template:
    src: "{{ mongod_systemd_template }}"
    dest: "/etc/systemd/system/{{ mongod_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart mongod service
