---
# Install dependencies via RPM and download MySQL connector

- name: Install Tomcat and Tomcat Native via RPM
  become: true
  ansible.builtin.package:
    name:
      - tomcat
      - tomcat-native
    state: present

- name: Ensure aa_dependencies directory exists
  become: true
  ansible.builtin.file:
    path: "{{ aa_dependencies_loc }}"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: '0755'

- name: Download mysql-connector
  become: true
  ansible.builtin.get_url:
    # The original url stopped working with get_url and curl (redirections are not working)
    url: https://cdn.mysql.com/archives/mysql-connector-java-5.1/mysql-connector-java-5.1.34.tar.gz
    dest: "{{ aa_dependencies_loc }}/mysql-connector-java-5.1.34.tar.gz"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: '0644'
