---

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart alarm server
  become: true
  ansible.builtin.systemd:
    name: "phoebus_alarm"
    state: restarted
    enabled: true

- name: Restart alarm logger
  become: true
  ansible.builtin.systemd:
    name: "phoebus_alarm_logger"
    state: restarted
    enabled: true

- name: Restart alarm config logger
  become: true
  ansible.builtin.systemd:
    name: "phoebus_alarm_config_logger"
    state: restarted
    enabled: true
