---
# tasks file for phoebus_alarm_service

- name: Install JDK dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.jdk_dependency
  when: not (skip_dependencies | default(false))

- name: Install Maven dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.maven_dependency
  when: not (skip_dependencies | default(false))

- name: Install Elasticsearch dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.elasticsearch_dependency
  when: not (skip_dependencies | default(false))

- name: Install Kafka dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.kafka_dependency
  when: not (skip_dependencies | default(false))

- name: Build CS-Studio Phoebus products
  ansible.builtin.include_role:
    name: nsls2.epics_services.cs_studio_phoebus
  when: not (skip_dependencies | default(false))

# Alarm Server

# create the installation location for the alarm server
- name: Ensure alarm server directory exists
  ansible.builtin.file:
    path: "{{ phoebus_alarm_install_dir }}/alarm_server"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0755"

# Copy binaries from /opt/css/lib/phoebus/services/alarm-server/target/service-alarm-server-{{ phoebus_alarm_server_version }}-bin.tar.gz
- name: Copy alarm server jar
  ansible.builtin.unarchive:
    src: "/opt/css/lib/phoebus/services/alarm-server/target/service-alarm-server-{{ phoebus_alarm_server_version }}-bin.tar.gz"
    dest: "{{ phoebus_alarm_install_dir }}/alarm_server"
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    extra_opts:
      - --strip-components=1

# create the installation location for the alarm logging server
- name: Ensure alarm logger directory exists
  ansible.builtin.file:
    path: "{{ phoebus_alarm_install_dir }}/alarm_logger"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0755"

# Copy binaries from /opt/css/lib/phoebus/services/alarm-server/target/service-alarm-logger-{{ phoebus_alarm_logger_version }}.jar
- name: Copy alarm logger server jar
  ansible.builtin.copy:
    src: "/opt/css/lib/phoebus/services/alarm-logger/target/service-alarm-logger-{{ phoebus_alarm_logger_version }}.jar"
    dest: "{{ phoebus_alarm_install_dir }}/alarm_logger/service-alarm-logger-{{ phoebus_alarm_logger_version }}.jar"
    remote_src: true
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# create the installation location for the alarm config logger server
- name: Ensure alarm config logger directory exists
  ansible.builtin.file:
    path: "{{ phoebus_alarm_install_dir }}/alarm_config_logger"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0755"

# Copy binaries from /opt/css/lib/phoebus/services/alarm-config-logger/target/service-alarm-config-logger-{{ phoebus_alarm_config_logger_version }}jar
- name: Copy alarm config logger server jar
  ansible.builtin.copy:
    src: "/opt/css/lib/phoebus/services/alarm-config-logger/target/service-alarm-config-logger-{{ phoebus_alarm_config_logger_version }}.jar"
    dest: "{{ phoebus_alarm_install_dir }}/alarm_config_logger/service-alarm-config-logger-{{ phoebus_alarm_config_logger_version }}.jar"
    remote_src: true
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# Create the alarm preferences
- name: Create the alarm server preferences file
  become: true
  ansible.builtin.template:
    src: phoebus_alarm_preferences.ini.j2
    dest: "{{ phoebus_alarm_install_dir }}/phoebus_alarm_preferences.ini"
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# Flush pending handlers so Kafka/ZK/ES are restarted before topic creation
- name: Ensure services are restarted before creating topics
  ansible.builtin.meta: flush_handlers

# Configure alarm topics
- name: Include tasks to configure alarm topics
  ansible.builtin.include_tasks: configure_topics.yml

# Configure alarm systemd services
- name: Include tasks to configure alarm systemd services
  ansible.builtin.include_tasks: configure_services.yml
