---
# defaults file for epics_tools_services_recceiver
recsync_addr_list: "255.255.255.255:5049,10.4.0.255:5049,127.255.255.255:5049"

cf_url: http://es01.cs.nsls2.local:8080/ChannelFinder
cf_user: cfstore
cf_password: password

epics_services_account: csstudio