---
# tasks file for epics_tools_services_elastic

- name: Import Elasticsearch GPG key
  become: true
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch yum repository
  become: true
  ansible.builtin.template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: "0644"
    owner: root
    group: root

- name: Install Elasticsearch
  become: true
  ansible.builtin.yum:
    name: "elasticsearch-{{ elastic_version }}"
    state: present
  notify:
    - Restart elasticsearch

- name: Ensure data directory exists
  become: true
  ansible.builtin.file:
    path: "{{ elastic_data }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: "0750"

- name: Ensure log directory exists
  become: true
  ansible.builtin.file:
    path: "{{ elastic_logs }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: "0750"

- name: Install the elasticsearch configuration
  become: true
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: "0660"
    owner: root
    group: elasticsearch
  notify:
    - Restart elasticsearch

- name: Configure Elasticsearch JVM heap size
  become: true
  ansible.builtin.template:
    src: jvm_heap.options.j2
    dest: /etc/elasticsearch/jvm.options.d/heap.options
    mode: "0644"
    owner: root
    group: elasticsearch
  notify:
    - Restart elasticsearch

- name: Enable elasticsearch service
  become: true
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    daemon_reload: true
