---
# tasks file for kafka_dependency

- name: Ensure kafka services directory exists
  ansible.builtin.file:
    path: /opt/epics-tools/services/{{ beamline_name }}/kafka
    state: directory
    mode: '0775'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Install kafka
  ansible.builtin.unarchive:
    src: https://downloads.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz
    dest: /opt/epics-tools/services/{{ beamline_name }}/kafka
    remote_src: true
    mode: '0775'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    extra_opts:
      - --strip-components=1
  notify:
    - Restart zookeeper
    - Restart kafka

- name: Ensure kafka logs directory has correct ownership
  become: true
  ansible.builtin.file:
    path: /opt/epics-tools/services/{{ beamline_name }}/kafka/logs
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    recurse: true

- name: Install the zookeeper configuration
  become: true
  ansible.builtin.template:
    src: zookeeper.properties
    dest: /opt/epics-tools/services/{{ beamline_name }}/kafka/config/zookeeper.properties
    mode: '0644'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  notify:
    - Restart zookeeper

- name: Install the kafka configuration
  become: true
  ansible.builtin.template:
    src: server.properties
    dest: /opt/epics-tools/services/{{ beamline_name }}/kafka/config/server.properties
    mode: '0644'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  notify:
    - Restart kafka

- name: Install the zookeeper systemd service
  become: true
  ansible.builtin.template:
    src: zookeeper.service
    dest: /etc/systemd/system/{{ beamline_name }}_zookeeper.service
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload systemd daemon
    - Restart zookeeper

- name: Install the kafka systemd service
  become: true
  ansible.builtin.template:
    src: kafka.service
    dest: /etc/systemd/system/{{ beamline_name }}_kafka.service
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload systemd daemon
    - Restart kafka
