---
# defaults file for phoebus_alarm_service

# java_home provided by jdk_dependency

# Path to CS-Studio Phoebus products (used to derive logback path)
cs_studio_phoebus_products_dest: "/opt/css/phoebus-products"

# Path to logback configuration
phoebus_logback: "{{ cs_studio_phoebus_products_dest }}/config/logback.xml"

# Alarm Server channel access options
alarm_epics_ca_addr_list: localhost

epics_services_account: csstudio

phoebus_alarm_install_dir: /opt/epics-tools/services/phoebus_alarm

zookeeper_port: 2181

kafka_install_dir: /opt/epics-tools/services/kafka
kafka_server: "localhost"
kafka_port: 9092

es_host: "localhost"
es_port: 9200

alarm_config: "Alarms"

alarm_mail_server: "localhost"
alarm_mail_server_port: 25
alarm_mail_server_from: "phoebus_alarm@localhost"

phoebus_alarm_server_version: 5.0.0
phoebus_alarm_server_jar: "service-alarm-server-{{ phoebus_alarm_server_version }}.jar"
phoebus_alarm_server_procServ_port: 60046

phoebus_alarm_logger_version: 5.0.0
phoebus_alarm_logger_jar: "service-alarm-logger-{{ phoebus_alarm_logger_version }}.jar"
phoebus_alarm_logger_procServ_port: 60047

phoebus_alarm_config_logger_version: 5.0.0
phoebus_alarm_config_logger_jar: "service-alarm-config-logger-{{ phoebus_alarm_config_logger_version }}.jar"
phoebus_alarm_config_logger_procServ_port: 60048
phoebus_alarm_config_local_repo: "{{ phoebus_alarm_install_dir }}/alarm_config_logger"
