---
# epics_services_account in vars/shared.yml

epics_ca_addr_list: localhost
epics_ca_max_array_bytes: 1000000

tomcat_dest: "{{ tomcat_home | default('/usr/share/tomcat') }}"
tomcat_service_name: tomcat

# PVWS (PV Web Socket) configuration
pvws_repo: "https://github.com/ControlSystemStudio/pvws-springboot.git"
# pvws_version, dbwr_version in vars/shared.yml
pvws_dest: /opt/css/pvws
pvws_mvn_args: "clean install -P war -DskipTests"

# DBWR (Display Builder Web Runtime) configuration
dbwr_repo: "https://github.com/ornl-epics/dbwr.git"
dbwr_dest: /opt/css/dbwr
dbwr_mvn_args: "clean install -DskipTests"
