---
# tasks file for epics_tools_services_recceiver

# procServ
- name: Install the latest version of python3-twisted
  yum:
    name: python3-twisted
    state: present

- name: Install the latest version of python3-requests
  yum:
    name: python3-requests
    state: present

- name: Install the latest version of python3-simplejson
  yum:
    name: python3-simplejson
    state: present

- name: Install the latest version of python3-urllib3
  yum:
    name: python3-urllib3
    state: present

- name: Clone the recsync installation repo
  become: true
  git:
    repo: 'https://github.com/ChannelFinder/RecSync-env.git'
    dest: /opt/epics-tools/services/recsync

- name: Run 'init' target as root
  make:
    chdir: /opt/epics-tools/services/recsync
    target: init
  become: yes

- name: Run 'install' target as root
  make:
    chdir: /opt/epics-tools/services/recsync
    target: install
  become: yes

# recsync conf
- name: copy recsync configuration
  become: true
  template:
    src: recsync.conf
    dest: /opt/RecSync/recsync.conf
    mode: 0755
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

# cf conf
- name: copy channel finder configuration
  become: true
  template:
    src: channelfinderapi.conf
    dest: /opt/RecSync/channelfinderapi.conf
    mode: 0755
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

# start recsync
- name: Restart recsync
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: "recsync"
