---
# Shared vars (epics_services_account, cs_studio_phoebus_products_dest,
# phoebus_logback, es_host, es_port, mongod_host, mongod_port)
# in vars/shared.yml

phoebus_olog_version: "v5.0.4"
phoebus_olog_jar: "service-olog-5.0.4.jar"

phoebus_olog_install_dir: /opt/epics-tools/services/phoebus_olog

# Olog REST service parameters
olog_http_port: 8080
olog_https_port: 8443

cors_allowed_origins: "http://localhost:3000"

## procServ port
olog_procServ_port: 60049

# Active Directory configuration (organization-specific)
ad_enabled: true
ad_url: ""
ad_domain: ""

# LDAP configuration (organization-specific)
ldap_enabled: false
ldap_urls: ""
ldap_base_dn: ""
