galaxy_info:
  author: NSLS-II
  description: Deploy the RecSync (recceiver) service
  company: Brookhaven National Laboratory
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - epics
    - recsync
    - channelfinder

dependencies: []
