---
# epics_services_account in vars/shared.yml

# Olog REST service parameters
phoebus_olog_url: "http://localhost:8080/Olog"
phoebus_olog_webclient_install_dir: /opt/epics-tools/services/phoebus_olog_webclient
phoebus_olog_webclient_project_path: "{{ phoebus_olog_webclient_install_dir }}/phoebus-olog-web-client"
# phoebus_olog_webclient_version in vars/shared.yml

# VITE build-time environment variables
phoebus_olog_webclient_endpoint: "Olog"
phoebus_olog_webclient_websocket_url: ""
phoebus_olog_webclient_support_href: ""
phoebus_olog_webclient_swagger_url: "/api/swagger-ui"

## procServ port
olog_webclient_procServ_port: 60050
