---
- name: Install procServ (run once per play)
  when: not (_procserv_dependency_done | default(false))
  block:
    - name: Install procServ
      become: true
      ansible.builtin.package:
        name: procServ
        state: present

    - name: Mark procserv dependency done
      ansible.builtin.set_fact:
        _procserv_dependency_done: true
