---
# defaults file for epics_tools_services_cf
beamline_name: "tst"
beamline_id: "31"

epics_services_account: epics-services-{{ beamline_name }}

cf_http_port: "1{{ beamline_id }}80"
cf_https_port: "1{{ beamline_id }}81"
# Channel Finder version
cf_version: ChannelFinder-4.7.3

cf_java_home: "/opt/epics-tools/lib/jvm/jdk-17"
cf_mvn_home: "/opt/epics-tools/lib/apache-maven-3.9.9"

# Path to logback configuration
phoebus_logback: "/opt/css/phoebus-products/config/logback.xml"

es_host: "localhost"
es_port: "4{{ beamline_id }}92"

# procServ port
cf_procServ_port: "1{{ beamline_id }}46"
