---
- name: Load shared collection defaults
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../../vars/shared.yml"

# tasks file for phoebus_web_runtime_service

- name: Install JDK dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.jdk_dependency
  when: not (skip_dependencies | default(false))

- name: Install Maven dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.maven_dependency
  when: not (skip_dependencies | default(false))

- name: Install Tomcat dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.tomcat_dependency
  when: not (skip_dependencies | default(false))

# PV Web Socket library
- name: Clone and/or update the pvws repo
  become: true
  become_user: "{{ epics_services_account }}"
  ansible.builtin.git:
    repo: "{{ pvws_repo }}"
    dest: "{{ pvws_dest }}"
    version: "{{ pvws_version }}"
    update: true
  register: _pvws_repo

# Display Builder Web Runtime library
- name: Clone and/or update the dbwr repo
  become: true
  become_user: "{{ epics_services_account }}"
  ansible.builtin.git:
    repo: "{{ dbwr_repo }}"
    dest: "{{ dbwr_dest }}"
    version: "{{ dbwr_version }}"
    update: true
  register: _dbwr_repo

# Build the pvws library
- name: Build the pvws binaries  # noqa: no-changed-when no-handler
  become: true
  become_user: "{{ epics_services_account }}"
  ansible.builtin.command: "mvn {{ pvws_mvn_args }}"
  args:
    chdir: "{{ pvws_dest }}/"
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  when: _pvws_repo.changed

# Build the dbwr library
- name: Build the dbwr binaries  # noqa: no-changed-when no-handler
  become: true
  become_user: "{{ epics_services_account }}"
  ansible.builtin.command: "mvn {{ dbwr_mvn_args }}"
  args:
    chdir: "{{ dbwr_dest }}/"
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  when: _dbwr_repo.changed

# Copy pvws.war to tomcat
- name: Copy pvws war  # noqa: no-handler
  become: true
  ansible.builtin.copy:
    src: "{{ pvws_dest }}/target/pvws.war"
    dest: "{{ tomcat_dest }}/webapps/pvws.war"
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"
  when: _pvws_repo.changed
  notify: Restart tomcat

# Copy dbwr.war to tomcat
- name: Copy dbwr war  # noqa: no-handler
  become: true
  ansible.builtin.copy:
    src: "{{ dbwr_dest }}/target/dbwr.war"
    dest: "{{ tomcat_dest }}/webapps/dbwr.war"
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"
  when: _dbwr_repo.changed
  notify: Restart tomcat

# Set up the environment variable
- name: Set environ variables
  become: true
  ansible.builtin.template:
    src: setenv.sh
    dest: "{{ tomcat_dest }}/bin/setenv.sh"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0755"
  notify: Restart tomcat
