---
# tasks file for phoebus_web_runtime_service

# PV Web Socket library
- name: Clone and/or update the pvws repo
  become: true
  ansible.builtin.git:
    repo: "{{ pvws_repo }}"
    dest: "{{ pvws_dest }}"
    force: true
    version: "{{ pvws_version }}"

# Display Builder Web Runtime library
- name: Clone and/or update the dbwr repo
  become: true
  ansible.builtin.git:
    repo: "{{ dbwr_repo }}"
    dest: "{{ dbwr_dest }}"
    force: true
    version: "{{ dbwr_version }}"

# Build the pvws library
- name: Build the pvws binaries
  ansible.builtin.command: mvn clean install
  args:
    chdir: "{{ pvws_dest }}/"
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  changed_when: true

# Build the dbwr library
- name: Build the dbwr binaries
  ansible.builtin.command: mvn clean install
  args:
    chdir: "{{ dbwr_dest }}/"
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  changed_when: true

# Copy pvws.war to tomcat
- name: Copy pvws war
  ansible.builtin.copy:
    src: "{{ pvws_dest }}/target/pvws.war"
    dest: "{{ tomcat_dest }}/webapps/{{ beamline_name }}#pvws.war"
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"

# Copy dbwr.war to tomcat
- name: Copy dbwr war
  ansible.builtin.copy:
    src: "{{ dbwr_dest }}/target/dbwr.war"
    dest: "{{ tomcat_dest }}/webapps/{{ beamline_name }}#dbwr.war"
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"

# Set up the environment variable
- name: Set environ variables
  ansible.builtin.template:
    src: setenv.sh
    dest: "{{ tomcat_dest }}/bin/setenv.sh"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0755"

# Restart tomcat
- name: Restart and enable tomcat
  ansible.builtin.service:
    daemon_reload: true
    name: "{{ tomcat_service_name }}"
    state: restarted
    enabled: true
  when: ansible_service_mgr == "systemd"
