---
# Shared vars (epics_services_account, es_host, es_port, ollama_host,
# ollama_port) in vars/shared.yml

springai_olog_repo: "https://github.com/alexariv/SpringAI.git"
springai_olog_version: "ologUI"
springai_olog_jar: "semantic-0.0.1-SNAPSHOT.jar"

springai_olog_install_dir: /opt/epics-tools/services/springai_olog

springai_olog_port: 8090
springai_olog_procServ_port: 60052

springai_ollama_model: "qwen3:8b"
springai_vector_index: "olog_vectors"
