---

- name: Check for repo dir
  ansible.builtin.stat:
    path: "{{ cs_studio_bobs_config.basedir + '/' + _repo.1 + '/' + _repo.0 }}"
  register: _stat

- name: Recursively change permissions
  ansible.builtin.file:
    dest: "{{ cs_studio_bobs_config.basedir + '/' + _repo.1 + '/' + _repo.0 }}"
    owner: root
    group: root
    mode: "u=rwX,g=rX,o=rX"
    recurse: true
  when: _stat.stat.exists

- name: Ensure proxy is unset
  community.general.git_config:
    repo: "{{ cs_studio_bobs_config.basedir + '/' + _repo.1 + '/' + _repo.0 }}"
    name: "{{ item }}.proxy"
    state: absent
    scope: local
  register: result
  loop:
    - http
    - https
  failed_when: false

- name: Clone bob repo
  ansible.builtin.git:
    repo: "{{ cs_studio_bobs_config.base_repo + '/' + _repo.0 + '.git' }}"
    dest: "{{ cs_studio_bobs_config.basedir + '/' + _repo.1 + '/' + _repo.0 }}"
    version: "{{ _repo.1 }}"
    update: true
