---
- name: Load shared collection defaults
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../../vars/shared.yml"


- name: Ensure basedir exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop:
    - "{{ cs_studio_bobs_config.basedir | dirname }}"
    - "{{ cs_studio_bobs_config.basedir }}"

- name: Install all cs-studio-repos
  ansible.builtin.include_tasks: bobs.yml
  loop: "{{ cs_studio_bobs_config.repos | product(cs_studio_bobs_config.version) | list }}"
  loop_control:
    loop_var: _repo
