---
# Install PyMySQL
- name: Install PyMySQL
  ansible.builtin.pip:
    name: PyMySQL

- name: Install the MariaDB client
  ansible.builtin.package:
    name: mariadb
    state: present

# Create the shift database
- name: Create shift database
  community.mysql.mysql_db:
    name: "{{ shift_jdbc_dbname }}"
    state: present
    login_host: "{{ shift_jdbc_server }}"
    login_user: root
    login_password: "{{ jdbc_root_user }}"

# Create the shift user and grant privileges
- name: Create shift MySQL user
  community.mysql.mysql_user:
    state: present
    name: "{{ shift_jdbc_user }}"
    password: "{{ shift_jdbc_password }}"
    priv: "{{ shift_jdbc_dbname }}.*:ALL,GRANT"
    host: "%"
    login_host: "{{ shift_jdbc_server }}"
    login_user: root
    login_password: "{{ jdbc_root_user }}"

# Create the shift schema
- name: Copy shift template to remote machine
  become: true
  ansible.builtin.template:
    src: shift-base.sql
    dest: "/tmp/{{ shift_jdbc_dbname }}_shift_schema.sql"
    mode: "0644"
