---
# configure the systemd services for the Olog Webclient services

- name: Install procServ
  ansible.builtin.include_role:
    name: nsls2.epics_services.procserv_dependency

# Olog Webclient

# setup run-phoebus-olog-webclient.sh
- name: Copy run-phoebus-olog-webclient.sh file
  become: true
  ansible.builtin.copy:
    src: run-phoebus-olog-webclient.sh
    dest: "{{ phoebus_olog_webclient_project_path }}/run-phoebus-olog-webclient.sh"
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  notify:
    - Restart phoebus_olog_webclient

- name: Copy build-run-phoebus-olog-webclient.sh file
  become: true
  ansible.builtin.copy:
    src: build-run-phoebus-olog-webclient.sh
    dest: "{{ phoebus_olog_webclient_project_path }}/build-run-phoebus-olog-webclient.sh"
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup systemd service file
- name: Create systemd olog webclient service files
  become: true
  ansible.builtin.template:
    src: phoebus_olog_webclient.service.j2
    dest: "/etc/systemd/system/phoebus_olog_webclient.service"
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  notify:
    - Reload systemd daemon
    - Restart phoebus_olog_webclient
