---
# tasks file for phoebus_olog_webclient_service

- name: Install Node.js
  ansible.builtin.include_role:
    name: nsls2.epics_services.nodejs_dependency

# create the installation location for the Olog Webclient server
- name: Ensure services folder exists
  ansible.builtin.file:
    path: "{{ phoebus_olog_webclient_install_dir }}"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    recurse: true

# Olog Webclient
- name: Clone and/or update the Olog webclient repo
  become: true
  become_user: "{{ epics_services_account }}"
  ansible.builtin.git:
    repo: 'https://github.com/Olog/phoebus-olog-web-client.git'
    dest: "{{ phoebus_olog_webclient_project_path }}"
    force: true
    version: "{{ phoebus_olog_webclient_version }}"
    update: true
  register: _webclient_repo

- name: Copy .env template file to the project folder
  become: true
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ phoebus_olog_webclient_project_path }}/.env"
    mode: "0644"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Install project dependencies with npm  # noqa: no-handler
  community.general.npm:
    path: "{{ phoebus_olog_webclient_project_path }}"
    production: false
  when: _webclient_repo.changed

- name: Run npm build script  # noqa: no-handler
  ansible.builtin.command: npm run build
  args:
    chdir: "{{ phoebus_olog_webclient_project_path }}"
  when: _webclient_repo.changed
  changed_when: true

# Setup and configure the Olog Webclient systemd services
- name: Include tasks to configure Olog Webclient systemd services
  ansible.builtin.include_tasks: configure_services.yml
