---
# Shared vars (epics_services_account, cs_studio_phoebus_products_dest,
# phoebus_logback, es_host, es_port) in vars/shared.yml

save_restore_java_home: "{{ java_home }}"

save_restore_install_dir: /opt/epics-tools/services/save_restore

# save_restore_version in vars/shared.yml
save_restore_jar: "{{ save_restore_install_dir }}/service-save-and-restore-{{ save_restore_version }}.jar"

save_restore_http_port: 8080
save_restore_https_port: 8443

## procServ port
save_restore_procServ_port: 60050

# Active Directory configuration (organization-specific)
ad_enabled: true
ad_url: ""
ad_domain: ""
