---
# configure the Kafka topics for the alarm services

- name: Create alarm topics script
  become: true
  ansible.builtin.template:
    src: create_alarm_topics.sh.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/create_alarm_topics.sh
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  register: _alarm_topics_script

- name: Create alarm topics
  become: true
  ansible.builtin.shell: >
    /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/create_alarm_topics.sh
    {{ alarm_config }}
    > /tmp/phoebus-create-topics.log 2>&1
  args:
    executable: /bin/bash
  when: _alarm_topics_script.changed
  changed_when: true
