---
# configure the systemd services for the alarm services

# procServ
- name: Install the latest version of procServ
  ansible.builtin.yum:
    name: procServ
    state: present

# Alarm Server

# setup run-phoebus-alarm.sh
- name: Create systemd service files
  become: true
  ansible.builtin.template:
    src: run-phoebus-alarm.sh.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_server/run-phoebus-alarm.sh
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup systemd service file
- name: Create systemd alarm server service files
  become: true
  ansible.builtin.template:
    src: phoebus_alarm.service.j2
    dest: /etc/systemd/system/{{ beamline_name }}_phoebus_alarm.service
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# start phoebus alarm server
- name: Restart alarm server
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ beamline_name }}_phoebus_alarm"

# Alarm Logger

# setup run-phoebus-alarm-logger.sh
- name: Create systemd service files
  become: true
  ansible.builtin.template:
    src: run-phoebus-alarm-logger.sh.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_logger/run-phoebus-alarm-logger.sh
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup systemd service file
- name: Create systemd alarm logger service files
  become: true
  ansible.builtin.template:
    src: phoebus_alarm_logger.service.j2
    dest: /etc/systemd/system/{{ beamline_name }}_phoebus_alarm_logger.service
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# start phoebus alarm logger
- name: Restart alarm server
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ beamline_name }}_phoebus_alarm_logger"

# Alarm Config Logger

# setup run-phoebus-alarm-config-logger.sh
- name: Create systemd service files
  become: true
  ansible.builtin.template:
    src: run-phoebus-alarm-config-logger.sh.j2
    dest: >
      /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_config_logger/run-phoebus-alarm-config-logger.sh
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup systemd service file
- name: Create systemd alarm config logger service files
  become: true
  ansible.builtin.template:
    src: phoebus_alarm_config_logger.service.j2
    dest: /etc/systemd/system/{{ beamline_name }}_phoebus_alarm_config_logger.service
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# start phoebus alarm logger
- name: Restart alarm config server
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ beamline_name }}_phoebus_alarm_config_logger"
