---
# tasks file for epics_tools_services_phoebus_alarm

# Alarm Server

# create the installation location for the alarm server
- name: Ensure alarm server directory exists
  ansible.builtin.file:
    path: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_server
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    recurse: true

# Copy binaries from /opt/css/lib/phoebus/services/alarm-server/target/service-alarm-server-{{ phoebus_alarm_server_version }}-bin.tar.gz
- name: Copy alarm server jar
  ansible.builtin.unarchive:
    src: "/opt/css/lib/phoebus/services/alarm-server/target/service-alarm-server-{{ phoebus_alarm_server_version }}-bin.tar.gz"
    dest: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_server
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    extra_opts:
      - --strip-components=1

# create the installation location for the alarm logging server
- name: Ensure alarm logger directory exists
  ansible.builtin.file:
    path: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_logger
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    recurse: true

# Copy binaries from /opt/css/lib/phoebus/services/alarm-server/target/service-alarm-logger-{{ phoebus_alarm_logger_version }}.jar
- name: Copy alarm logger server jar
  ansible.builtin.copy:
    src: "/opt/css/lib/phoebus/services/alarm-logger/target/service-alarm-logger-{{ phoebus_alarm_logger_version }}.jar"
    dest: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_logger/service-alarm-logger-{{ phoebus_alarm_logger_version }}.jar
    remote_src: true
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# create the installation location for the alarm config logger server
- name: Ensure alarm config logger directory exists
  ansible.builtin.file:
    path: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_config_logger
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    recurse: true

# Copy binaries from /opt/css/lib/phoebus/services/alarm-config-logger/target/service-alarm-config-logger-{{ phoebus_alarm_config_logger_version }}jar
- name: Copy alarm config logger server jar
  ansible.builtin.copy:
    src: "/opt/css/lib/phoebus/services/alarm-config-logger/target/service-alarm-config-logger-{{ phoebus_alarm_config_logger_version }}.jar"
    dest: >-
      /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/alarm_config_logger/service-alarm-config-logger-{{ phoebus_alarm_config_logger_version }}.jar
    remote_src: true
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# Create the alarm preferences
- name: Create the alarm server preferences file
  become: true
  ansible.builtin.template:
    src: phoebus_alarm_preferences.ini.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/phoebus_alarm/phoebus_alarm_preferences.ini
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# Configure alarm topics
- name: Include tasks to configure alarm topics
  ansible.builtin.include_tasks: configure_topics.yml

# Configure alarm systemd services
- name: Include tasks to configure alarm systemd services
  ansible.builtin.include_tasks: configure_services.yml
