---
# configure the systemd services for the Olog services

- name: Install procServ
  ansible.builtin.include_role:
    name: nsls2.epics_services.procserv_dependency

# Olog Server

# setup run-phoebus-olog.sh
- name: Create run-phoebus-olog service files
  become: true
  ansible.builtin.template:
    src: run-phoebus-olog.sh.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/olog/run-phoebus-olog.sh
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup olog properties
- name: Create olog.properties
  become: true
  ansible.builtin.template:
    src: olog.properties.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/olog/olog.properties
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup systemd service file
- name: Create systemd olog server service files
  become: true
  ansible.builtin.template:
    src: phoebus_olog.service.j2
    dest: /etc/systemd/system/{{ beamline_name }}_phoebus_olog.service
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# start olog server
- name: Restart alarm server
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ beamline_name }}_phoebus_olog"
