---
# tasks file for phoebus_olog_service

# create the installation location for the alarm server
- name: Ensure services folder exists
  ansible.builtin.file:
    path: /opt/epics-tools/services/{{ beamline_name }}/olog
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    recurse: true

# Olog
- name: Clone and/or update the Olog service repo
  become: true
  become_user: "{{ epics_services_account }}"
  ansible.builtin.git:
    repo: 'https://github.com/Olog/phoebus-olog.git'
    dest: /opt/epics-tools/services/{{ beamline_name }}/olog/phoebus-olog
    force: true
    version: "{{ phoebus_olog_version }}"
    update: true

# build the Olog library
- name: Build the Olog binaries
  become: true
  become_user: "{{ epics_services_account }}"
  ansible.builtin.command: mvn clean install -Pdeployable-jar -DskipTests
  args:
    chdir: /opt/epics-tools/services/{{ beamline_name }}/olog/phoebus-olog
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  changed_when: true

# copy binaries from /opt/epics-tools/services/{{ beamline_name }}/olog/phoebus-olog/target/service-olog-5.0.*.jar
- name: Copy phoebus olog server jar
  become: true
  ansible.builtin.copy:
    src: "/opt/epics-tools/services/{{ beamline_name }}/olog/phoebus-olog/target/{{ phoebus_olog_jar }}"
    dest: "/opt/epics-tools/services/{{ beamline_name }}/olog/{{ phoebus_olog_jar }}"
    force: true
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    remote_src: true

# Setup and configure the Olog systemd services
- name: Include tasks to configure Olog systemd services
  ansible.builtin.include_tasks: configure_services.yml
