---

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart phoebus_olog
  become: true
  ansible.builtin.systemd:
    name: "phoebus_olog"
    state: restarted
    enabled: true
