---
# defaults file for epics_tools_services_phoebus_alarm
beamline_name: "tst"
beamline_id: "31"

# Locations from epics_tools_libs
java_home: "/opt/epics-tools/lib/jvm/jdk-17"
mvn_home: "/opt/epics-tools/lib/apache-maven-3.9.9"

epics_tools_services_phoebus_olog_version: "v5.0.4"
epics_tools_services_phoebus_olog_jar: "service-olog-5.0.4.jar"

# Alarm Server channel access options
alarm_epics_ca_addr_list: localhost
epics_services_account: csstudio

# Olog REST service parameters
olog_http_port: "4{{ beamline_id }}80"
olog_https_port: "4{{ beamline_id }}81"

cors_allowed_origins: "http://localhost:3000"

es_host: "localhost"
es_port: 4{{ beamline_id }}92

mongod_host: "localhost"
mongod_port: 2{{ beamline_id }}17

## procServ port
olog_procServ_port: "4{{ beamline_id }}46"
