---
# defaults file for epics_tools_services_kafka

beamline_name: tst

epics_services_account: csstudio

kafka_java_home: "/opt/epics-tools/lib/jvm/jdk-17"

zookeeper_port: 2181
zookeeper_data: /opt/epics-tools/services/{{ beamline_name }}/kafka/data/zookeeper

kafka_port: 9092
kafka_logs: /opt/epics-tools/services/{{ beamline_name }}/kafka/kafka-logs
