---
# defaults file for epics_tools_services_kafka

beamline_name: tst
beamline_id: "31"

epics_services_account: csstudio

zookeeper_port: 4{{beamline_id}}93
zookeeper_data: /opt/epics-tools/services/{{ beamline_name }}/kafka/data/zookeeper

kafka_port: 4{{beamline_id}}94
kafka_logs: /opt/epics-tools/services/{{ beamline_name }}/kafka/kafka-logs