---
# defaults file for kafka_dependency

epics_services_account: csstudio

kafka_java_home: "/usr/lib/jvm/java-21-openjdk"

kafka_install_dir: /opt/epics-tools/services/kafka

zookeeper_port: 2181
zookeeper_data: "{{ kafka_install_dir }}/data/zookeeper"

kafka_port: 9092
kafka_logs: "{{ kafka_install_dir }}/kafka-logs"
