---
# defaults file for mongodb_dependency

mongodb_version: "8.0"

epics_services_account: csstudio

mongod_port: 27017
mongod_user: "mongod"
mongod_group: "mongod"
mongod_service: "mongod"
mongod_name: "mongod"
bind_ip: 0.0.0.0
bind_ip_all: false
repl_set_name: rs0
mongod_package: "mongodb-org-server"
replicaset: false

mongod_home: "/var/lib/mongodb"
mongod_data_path: "{{ mongod_home }}/data"

mongod_config_template: "mongod.conf.j2"
mongod_systemd_template: "mongod.service.j2"
