---
# tasks file for epics_tools_services_glassfish
- name: ensure services directory exists
  file:
    path: /opt/epics-tools/services/{{beamline_name}}
    state: directory
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

- name: install open galssfish 5.0.1
  ansible.builtin.unarchive:
    src: http://download.oracle.com/glassfish/5.0.1/release/glassfish-5.0.1.zip
    dest: /opt/epics-tools/services/{{beamline_name}}/
    remote_src: yes
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

- name: install the fixed bootstrap file
  copy:
    src: grizzly-npn-bootstrap.jar
    dest: /opt/epics-tools/services/{{beamline_name}}/glassfish5/glassfish/modules/endorsed/grizzly-npn-bootstrap.jar
    force: true
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

# install jdbc connectors and third party libraries
- name: install jdbc connectors and third party libraries
  include: install_connectors.yml

# setup and configure the mysql server
- name: setup and configure the mysql server
  include: configure_mysql.yml
  when: configure_mysql

- name: Check if Service Glassfish Exists
  stat: path=/etc/systemd/system/"{{beamline_name}}_glassfish"
  register: service_status

- name: Stop service glassfish, if running
  systemd:
    name: "{{beamline_name}}_glassfish"
    state: stopped
  when: service_status.stat.exists
  register: service_stopped

# setup the domain.xml
- name: setup glassfish domain.xml
  become: true
  template:
    src: domain.xml
    dest: /opt/epics-tools/services/{{beamline_name}}/glassfish5/glassfish/domains/domain1/config/domain.xml

# install shift war
- name: Download shift war
  get_url:
    url: https://sourceforge.net/projects/olog/files/shift/Shift-1.1.war/download
    dest: /opt/epics-tools/services/{{beamline_name}}/glassfish5/glassfish/domains/domain1/autodeploy/Shift-1.1.war
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

# setup systemd service file
- name: create systemd service files
  become: true
  template:
    src: glassfish.service
    dest: /etc/systemd/system/{{beamline_name}}_glassfish.service
    mode: 0755
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

# start glassfish
- name: Restart glassfish
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: "{{beamline_name}}_glassfish"
