---
# Download dependencies

- name: Ensure aa_build directory exists
  ansible.builtin.file:
    path: "{{ aa_build_loc }}"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: '0755'

- name: Clone and/or update the aa repo
  become: true
#  become_user: csstudio
  ansible.builtin.git:
    repo: 'https://github.com/archiver-appliance/epicsarchiverap.git'
    dest: "{{ aa_build_loc }}/epicsarchiverap"
    version: "{{ aa_version }}"
    force: true

- name: Cleanup build directory
  ansible.builtin.file:
    path: "{{ aa_build_loc }}/epicsarchiverap/build"
    state: absent

- name: Build
  ansible.builtin.command:
    chdir: "{{ aa_build_loc }}/epicsarchiverap"
    cmd: ./gradlew -x sphinx
  environment:
    JAVA_HOME: "{{ aa_java_home }}"
    TOMCAT_HOME: "{{ aa_tomcat_home }}"
  changed_when: true
