---
# configure the systemd services for the ChannelFinder services

- name: Install procServ
  ansible.builtin.include_role:
    name: nsls2.epics_services.procserv_dep

# ChannelFinder Server

# setup run-cf.sh
- name: Create run-cf service files
  become: true
  ansible.builtin.template:
    src: run-cf.sh.j2
    dest: "{{ channelfinder_install_dir }}/run-cf.sh"
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  notify:
    - Restart channelfinder

# setup cf properties
- name: Create cf.properties
  become: true
  ansible.builtin.template:
    src: cf.properties.j2
    dest: "{{ channelfinder_install_dir }}/cf.properties"
    mode: "0644"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  notify:
    - Restart channelfinder

# setup systemd service file
- name: Create systemd cf server service files
  become: true
  ansible.builtin.template:
    src: cf.service.j2
    dest: /etc/systemd/system/channelfinder.service
    mode: "0644"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
  notify:
    - Reload systemd daemon
    - Restart channelfinder
