---
# defaults file for channelfinder_service

epics_services_account: csstudio

channelfinder_install_dir: /opt/epics-tools/services/channelfinder

cf_http_port: 8080
cf_https_port: 8443
# Channel Finder version
cf_version: ChannelFinder-4.7.3

cf_java_home: "{{ java_home }}"
cf_mvn_home: "{{ mvn_home }}"

# Path to logback configuration
phoebus_logback: "/opt/css/phoebus-products/config/logback.xml"

es_host: "localhost"
es_port: 9200

# procServ port
cf_procServ_port: 60051
