---
# Shared vars (epics_services_account, cs_studio_phoebus_products_dest,
# phoebus_logback, es_host, es_port) in vars/shared.yml

channelfinder_install_dir: /opt/epics-tools/services/channelfinder

cf_http_port: 8080
cf_https_port: 8443
# Channel Finder version
cf_version: ChannelFinder-5.0.0

cf_java_home: "{{ java_home }}"
cf_mvn_home: "{{ mvn_home }}"

# procServ port
cf_procServ_port: 60051
