---
# tasks file for epics_tools_services_kafka

- name: Ensure services directory exists
  ansible.builtin.file:
    path: /opt/epics-tools/services/{{ beamline_name }}/kafka
    state: directory
    mode: '0775'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Install kafka search
  ansible.builtin.unarchive:
    src: https://downloads.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz
    dest: /opt/epics-tools/services/{{ beamline_name }}/kafka
    remote_src: true
    mode: '0775'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    extra_opts:
      - --strip-components=1

- name: Install the zookeeper configuration
  become: true
  ansible.builtin.template:
    src: zookeeper.properties
    dest: /opt/epics-tools/services/{{ beamline_name }}/kafka/config/zookeeper.properties
    mode: '0644'
    force: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Install the kafka configuration
  become: true
  ansible.builtin.template:
    src: server.properties
    dest: /opt/epics-tools/services/{{ beamline_name }}/kafka/config/server.properties
    force: true
    mode: '0644'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Install the systemd startup scripts
  become: true
  ansible.builtin.template:
    src: zookeeper.service
    dest: /etc/systemd/system/{{ beamline_name }}_zookeeper.service
    force: true
    mode: '0755'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Install the systemd startup scripts
  become: true
  ansible.builtin.template:
    src: kafka.service
    dest: /etc/systemd/system/{{ beamline_name }}_kafka.service
    force: true
    mode: '0755'
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: Install and restart services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - "{{ beamline_name }}_zookeeper"
    - "{{ beamline_name }}_kafka"

