---
- name: Load shared collection defaults
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../../vars/shared.yml"

- name: Flush the dbwr cache
  ansible.builtin.uri:
    url: "{{ item }}/cache"
    method: DELETE
  loop: "{{ phoebus_dbwr_urls }}"
  failed_when: false
