---
# maven_version and mvn_home moved to vars/shared.yml

maven_url: "https://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
maven_dependency_owner: "{{ epics_services_account }}"
