---
# configure the systemd services for the ChannelFinder services

- name: Install procServ
  ansible.builtin.include_role:
    name: nsls2.epics_services.procserv_dependency

# ChannelFinder Server

# setup run-cf.sh
- name: Create run-cf service files
  become: true
  ansible.builtin.template:
    src: run-cf.sh.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/cf/run-cf.sh
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup cf properties
- name: Create cf.properties
  become: true
  ansible.builtin.template:
    src: cf.properties.j2
    dest: /opt/epics-tools/services/{{ beamline_name }}/cf/cf.properties
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# setup systemd service file
- name: Create systemd cf server service files
  become: true
  ansible.builtin.template:
    src: cf.service.j2
    dest: /etc/systemd/system/{{ beamline_name }}_cf.service
    mode: "0755"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

# start cf server
- name: Restart channelfinder server
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ beamline_name }}_cf"
