---
# tasks file for epics_tools_services_aa

# download build and install dependencies
- include: dependencies.yml
- include: configure_mysql.yml

# configure SSL certificates if enabled
- include: configure_ssl.yml

# build aa
# TODO: replace with the use of prebuilt binaries
- include: build_aa.yml

# install and deploy aa
- include: install_aa.yml
