---
# epics_services_account in vars/shared.yml

recsync_install_dir: /opt/epics-tools/services/recsync
recsync_runtime_dir: /opt/RecSync
recsync_repo: "https://github.com/ChannelFinder/RecSync-env.git"
# recsync_version in vars/shared.yml

# RecSync broadcast addresses
recsync_addr_list: ""

# ChannelFinder connection
cf_url: ""
cf_user: cfstore
cf_password: password
