---
# tasks file for epics_tools_services_phoebus_web_runtime

# TODO fork into nsls2
# pv web socket library
- name: Clone and/or update the nsls2 pvws repo
  become: true
  git:
    repo: 'https://github.com/shroffk/pvws.git'
    dest: /opt/css/nsls2-pvws
    force: yes
    version: "{{ pvws_version }}"

# TODO fork into nsls2
# display builder web runtime library
- name: Clone and/or update the nsls2 dbwr repo
  become: true
  git:
    repo: 'https://github.com/shroffk/dbwr.git'
    dest: /opt/css/nsls2-dbwr
    force: yes
    version: "{{ dbwr_version }}"

- name: print maven info
  command: mvn clean install
  args:
    chdir: /opt/css/nsls2-pvws/
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
    
# build the pvws library
- name: build the pvws binaries
  command: mvn clean install
  args:
    chdir: /opt/css/nsls2-pvws/
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"

# build the dbwr library
- name: build the dbwr binaries
  command: mvn clean install
  args:
    chdir: /opt/css/nsls2-dbwr/
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"

# copy binaries from /opt/css/nsls2-pvws/pvws.war
- name: copy pvws war
  ansible.builtin.copy:
    src: /opt/css/nsls2-pvws/target/pvws.war
    dest: "{{ tomcat_dest }}/webapps/{{ beamline_name }}#pvws.war"
    remote_src: yes
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

# copy binaries from /opt/css/nsls2-dbwr/dbwr.war
- name: copy pvws war
  ansible.builtin.copy:
    src: /opt/css/nsls2-dbwr/target/dbwr.war
    dest: "{{ tomcat_dest }}/webapps/{{ beamline_name }}#dbwr.war"
    remote_src: yes
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

# set up the environment variable
- name: Set environ variables
  template:
    src: setenv.sh
    dest: "{{ tomcat_dest }}/bin/setenv.sh"
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"
    mode: 0755

#restart tomcat
- name: restart and enable tomcat
  service:
    daemon_reload: yes
    name: "{{ tomcat_service_name }}"
    state: restarted
    enabled: yes
  when: ansible_service_mgr == "systemd"
