---
# Download dependencies

- name: Ensure aa_build directory exists
  ansible.builtin.file:
    path: "{{ aa_build_loc }}"
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: '0755'

- name: Clone and/or update the aa repo
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/archiver-appliance/epicsarchiverap.git'
    dest: "{{ aa_build_loc }}/epicsarchiverap"
    version: "{{ aa_version }}"
  register: _repo

- name: Cleanup build directory  # noqa: no-handler
  ansible.builtin.file:
    path: "{{ aa_build_loc }}/epicsarchiverap/build"
    state: absent
  when: _repo.changed

- name: Build  # noqa: no-changed-when no-handler
  ansible.builtin.command:
    chdir: "{{ aa_build_loc }}/epicsarchiverap"
    cmd: ./gradlew -x sphinx
  environment:
    JAVA_HOME: "{{ aa_java_home }}"
    TOMCAT_HOME: "{{ aa_tomcat_home }}"
  when: _repo.changed
