---
# Install AA-specific dependencies via RPM packages

- name: Install Tomcat via RPM
  become: true
  ansible.builtin.package:
    name:
      - tomcat
    state: present

- name: Install MariaDB JDBC connector via RPM
  become: true
  ansible.builtin.package:
    name:
      - mariadb-java-client
    state: present
