---
# tasks file for aa_service

- name: Install JDK dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.jdk_dependency
  when: not (skip_dependencies | default(false))

- name: Install Tomcat dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.tomcat_dependency
  when: not (skip_dependencies | default(false))

- name: Install MariaDB JDBC dependency
  ansible.builtin.include_role:
    name: nsls2.epics_services.mariadb_dependency
  when: not (skip_dependencies | default(false))

- name: Configure local MariaDB
  ansible.builtin.include_tasks: configure_mysql.yml

- name: Build Archiver Appliance
  ansible.builtin.include_tasks: build.yml

- name: Pre-upgrade data consolidation
  ansible.builtin.include_tasks: pre_upgrade.yml
  when: _repo.changed and aa_pre_upgrade_consolidate | bool

- name: Deploy Archiver Appliance
  ansible.builtin.include_tasks: deploy.yml

- name: Post-upgrade PV resume
  ansible.builtin.include_tasks: post_upgrade.yml
  when: _repo.changed and aa_pre_upgrade_consolidate | bool

- name: Configure custom logging
  ansible.builtin.include_tasks: configure_logging.yml
  when: aa_configure_custom_logs | bool
