---
# tasks file for epics_tools_libs

- name: Install OpenJDK packages
  become: true
  ansible.builtin.yum:
    name: "{{ jdk_packages | map(attribute='package') | list }}"
    state: present

- name: Ensure JVM symlink directory exists
  ansible.builtin.file:
    path: "{{ jdk_symlink_base }}"
    state: directory
    owner: "{{ epics_tools_libs_epics_services_account }}"
    group: "{{ epics_tools_libs_epics_services_account }}"
    mode: "u=rwX,g=rwX,o=rX"

- name: Create compatibility symlinks for JDK paths
  ansible.builtin.file:
    src: "{{ item.rpm_path }}"
    dest: "{{ jdk_symlink_base }}/jdk-{{ item.version }}"
    state: link
    force: true
  loop: "{{ jdk_packages }}"

- name: Ensure Maven directory exists
  ansible.builtin.file:
    path: "/opt/epics-tools/lib/apache-maven-{{ maven_version }}"
    state: directory
    owner: "{{ epics_tools_libs_epics_services_account }}"
    group: "{{ epics_tools_libs_epics_services_account }}"
    mode: "u=rwX,g=rwX,o=rX"

- name: Install Maven
  ansible.builtin.unarchive:
    src: "{{ maven_url }}"
    dest: "/opt/epics-tools/lib/apache-maven-{{ maven_version }}"
    creates: "/opt/epics-tools/lib/apache-maven-{{ maven_version }}/bin/mvn"
    remote_src: true
    owner: "{{ epics_tools_libs_epics_services_account }}"
    group: "{{ epics_tools_libs_epics_services_account }}"
    extra_opts:
      - --strip-components=1
