---
# install PyMySQL
- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: Install the mysql client
  yum:
    name: mysql
    state: present

# create the shift database
- name: Create a new database with name {{shift_jdbc_dbname}}
  mysql_db:
    name: "{{shift_jdbc_dbname}}"
    state: present
    login_host: "{{shift_jdbc_server}}"
    login_user: root
    login_password: "{{jdbc_root_user}}"

# create the shift users and grant prvilidges
- name: Create shift mysql user
  mysql_user:
    state: present
    name: "{{shift_jdbc_user}}"
    password: "{{shift_jdbc_password}}"
    priv: '{{shift_jdbc_dbname}}.*:ALL,GRANT'
    host: '%'
    login_host: "{{shift_jdbc_server}}"
    login_user: root
    login_password: "{{jdbc_root_user}}"

# create the shift schema
- name: Copy shift template to remote machine
  become: true
  template:
    src: shift-base.sql
    dest: /tmp/{{shift_jdbc_dbname}}_shift_schema.sql
