---
# Install connectors and third party libraries

- name: Download xercesImpl
  ansible.builtin.get_url:
    url: https://repo1.maven.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
    dest: "{{ shift_install_dir }}/glassfish5/glassfish/lib"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"

- name: Download MySQL JDBC connector
  ansible.builtin.get_url:
    url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar
    dest: "{{ shift_install_dir }}/glassfish5/glassfish/lib/mysql-connector-java-5.1.34-bin.jar"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"
