---
# Install connectors and third party libraries

- name: Download xercesImpl
  ansible.builtin.get_url:
    url: https://repo1.maven.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
    dest: "{{ shift_install_dir }}/glassfish5/glassfish/lib"
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"

- name: Copy MariaDB JDBC connector to GlassFish lib
  become: true
  ansible.builtin.copy:
    src: "{{ shift_mysql_connector_jar }}"
    dest: "{{ shift_install_dir }}/glassfish5/glassfish/lib/mariadb-java-client.jar"
    remote_src: true
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"
    mode: "0644"
